# DB connection
spring.data.mongodb:
  database: users
  host: localhost
  port: 27017

management.port: 8081
management.address: 127.9.0.1
management.context-path: /actuator
#endpoints.health.enabled: false

security.user.name: admin
security.user.password: admin

management.security.enabled: false